services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:     # permanent storage data
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .    # build Docker image based on Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app # synchronize current directory with /app in the container
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:  # forcing db container to start before web
      - db

volumes:
  postgres_data: